"""add displayed_name to users

Revision ID: 0acc9dc17320
Revises: 7a5f772002de
Create Date: 2025-03-13 12:03:51.734288

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0acc9dc17320"
down_revision: Union[str, None] = "7a5f772002de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app1_user",
        sa.Column(
            "Displayed user name",
            sa.String(length=50),
            server_default="Noname",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app1_user", "Displayed user name")
    # ### end Alembic commands ###
