"""rubric, rub_pro_association added, products edited

Revision ID: 86832991ce9b
Revises: 2b43d6e8bcb3
Create Date: 2025-03-27 17:35:28.826605

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86832991ce9b"
down_revision: Union[str, None] = "2b43d6e8bcb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app1_rubric",
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.CheckConstraint(
            "length(title) >= 3",
            name=op.f("ck_app1_rubric_check_title_min_length"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app1_rubric")),
        sa.UniqueConstraint("title", name=op.f("uq_app1_rubric_title")),
    )
    op.create_table(
        "app1_rubric_image",
        sa.Column("rubric_id", sa.Integer(), nullable=False),
        sa.Column("file", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rubric_id"],
            ["app1_rubric.id"],
            name=op.f("fk_app1_rubric_image_rubric_id_app1_rubric"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app1_rubric_image")),
        sa.UniqueConstraint(
            "rubric_id", name=op.f("uq_app1_rubric_image_rubric_id")
        ),
    )
    op.create_table(
        "app1_rubric_product_association",
        sa.Column("rubric_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["app1_product.id"],
            name=op.f(
                "fk_app1_rubric_product_association_product_id_app1_product"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["rubric_id"],
            ["app1_rubric.id"],
            name=op.f(
                "fk_app1_rubric_product_association_rubric_id_app1_rubric"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_app1_rubric_product_association")
        ),
        sa.UniqueConstraint(
            "rubric_id", "product_id", name="idx_unique_rubric_product"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app1_rubric_product_association")
    op.drop_table("app1_rubric_image")
    op.drop_table("app1_rubric")
    # ### end Alembic commands ###
