"""create access_token table

Revision ID: 7a5f772002de
Revises: d9a5a51d7d59
Create Date: 2025-03-11 13:18:16.489744

"""

from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a5f772002de"
down_revision: Union[str, None] = "d9a5a51d7d59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app1_access_token",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=43), nullable=False),
        sa.Column(
            "created_at",
            fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app1_user.id"],
            name=op.f("fk_app1_access_token_user_id_app1_user"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("token", name=op.f("pk_app1_access_token")),
    )
    op.create_index(
        op.f("ix_app1_access_token_created_at"),
        "app1_access_token",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_app1_access_token_created_at"), table_name="app1_access_token"
    )
    op.drop_table("app1_access_token")
    # ### end Alembic commands ###
