"""create users table

Revision ID: dcda53283685
Revises:
Create Date: 2025-03-07 12:59:32.253211

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dcda53283685"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app1_user",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("foo", sa.String(), server_default="foo", nullable=False),
        sa.Column("bar", sa.String(), server_default="bar", nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app1_user")),
        sa.UniqueConstraint("foo", "bar", name=op.f("uq_app1_user_foo_bar")),
        sa.UniqueConstraint("username", name=op.f("uq_app1_user_username")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app1_user")
    # ### end Alembic commands ###
