"""product-brand relation added

Revision ID: 534ca7402ad0
Revises: 86832991ce9b
Create Date: 2025-03-28 10:34:57.849094

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "534ca7402ad0"
down_revision: Union[str, None] = "86832991ce9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app1_product", sa.Column("brand_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_app1_product_brand_id_app1_brand"),
        "app1_product",
        "app1_brand",
        ["brand_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_app1_product_brand_id_app1_brand"),
        "app1_product",
        type_="foreignkey",
    )
    op.drop_column("app1_product", "brand_id")
    # ### end Alembic commands ###
