"""session table added

Revision ID: ec19d28aef38
Revises: 534ca7402ad0
Create Date: 2025-04-03 21:33:19.604414

"""

from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ec19d28aef38"
down_revision: Union[str, None] = "534ca7402ad0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app1_session",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("user_email", sa.String(), nullable=True),
        sa.Column("data", sa.String(), nullable=False),
        sa.Column(
            "expired_at",
            fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app1_user.id"],
            name=op.f("fk_app1_session_user_id_app1_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_app1_session")),
        sa.UniqueConstraint("user_id", name=op.f("uq_app1_session_user_id")),
    )
    op.create_index(
        op.f("ix_app1_session_expired_at"),
        "app1_session",
        ["expired_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_app1_session_expired_at"), table_name="app1_session"
    )
    op.drop_table("app1_session")
    # ### end Alembic commands ###
