"""renamed display_name in users

Revision ID: b85fcf2ff8de
Revises: cc66f3f4e5eb
Create Date: 2025-03-13 13:04:25.463368

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b85fcf2ff8de"
down_revision: Union[str, None] = "cc66f3f4e5eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app1_user",
        sa.Column(
            "display_name",
            sa.String(length=50),
            server_default="Noname",
            nullable=False,
        ),
    )
    op.drop_column("app1_user", "displayed_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app1_user",
        sa.Column(
            "displayed_name",
            sa.VARCHAR(length=50),
            server_default=sa.text("'Noname'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("app1_user", "display_name")
    # ### end Alembic commands ###
