"""brands, products, images tables added

Revision ID: 37bddd3fed8c
Revises: b85fcf2ff8de
Create Date: 2025-03-27 10:11:55.582169

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "37bddd3fed8c"
down_revision: Union[str, None] = "b85fcf2ff8de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app1_brand",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.CheckConstraint(
            "length(title) >= 3",
            name=op.f("ck_app1_product_check_title_min_length"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app1_brand")),
        sa.UniqueConstraint("title", name=op.f("uq_app1_brand_title")),
    )
    op.create_table(
        "app1_product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.CheckConstraint(
            "length(title) >= 3",
            name=op.f("ck_app1_product_check_title_min_length"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app1_product")),
        sa.UniqueConstraint("title", name=op.f("uq_app1_product_title")),
    )
    op.create_table(
        "app1_brand_image",
        sa.Column("brand_id", sa.Integer(), nullable=False),
        sa.Column("file", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["app1_brand.id"],
            name=op.f("fk_app1_brand_image_brand_id_app1_brand"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app1_brand_image")),
        sa.UniqueConstraint(
            "brand_id", name=op.f("uq_app1_brand_image_brand_id")
        ),
    )
    op.create_table(
        "app1_product_image",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("file", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["app1_product.id"],
            name=op.f("fk_app1_product_image_product_id_app1_product"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app1_product_image")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app1_product_image")
    op.drop_table("app1_brand_image")
    op.drop_table("app1_product")
    op.drop_table("app1_brand")
    # ### end Alembic commands ###
