"""brands, products, images tables ondelete added

Revision ID: 9e13b02622f2
Revises: d28e6449af71
Create Date: 2025-03-26 11:05:09.444824

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e13b02622f2"
down_revision: Union[str, None] = "d28e6449af71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_app1_brand_image_brand_id_app1_brand",
        "app1_brand_image",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_app1_brand_image_brand_id_app1_brand"),
        "app1_brand_image",
        "app1_brand",
        ["brand_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_app1_product_image_product_id_app1_product",
        "app1_product_image",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_app1_product_image_product_id_app1_product"),
        "app1_product_image",
        "app1_product",
        ["product_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_app1_product_image_product_id_app1_product"),
        "app1_product_image",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_app1_product_image_product_id_app1_product",
        "app1_product_image",
        "app1_product",
        ["product_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_app1_brand_image_brand_id_app1_brand"),
        "app1_brand_image",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_app1_brand_image_brand_id_app1_brand",
        "app1_brand_image",
        "app1_brand",
        ["brand_id"],
        ["id"],
    )
    # ### end Alembic commands ###
